"""Lightweight mock GenAI client for tests and local development."""
import json
from types import SimpleNamespace
from typing import Any, Optional


class MockModels:
    def __init__(self, response_text: Optional[str] = None, candidates: Optional[list] = None, raise_error: Optional[Exception] = None):
        self._response_text = response_text
        self._candidates = candidates or []
        self._raise_error = raise_error

    async def generate_content(self, *args, **kwargs) -> Any:
        if self._raise_error:
            raise self._raise_error

        # Return object similar to real genai response
        resp = SimpleNamespace()
        # If _response_text is None, provide a default JSON. If it's an
        # empty string we should preserve it (tests rely on empty-text behavior).
        if self._response_text is None:
            resp.text = json.dumps({
                "title": "Mock Title",
                "description": "Mock description generated by MockGenaiClient."
            })
        else:
            resp.text = self._response_text
        resp.candidates = self._candidates

        return resp


class MockGenaiClient:
    """Async context manager that exposes `.models.generate_content`.

    Usage: `async with MockGenaiClient(...).aio as client:`
    """

    def __init__(self, response_text: Optional[str] = None, candidates: Optional[list] = None, raise_error: Optional[Exception] = None):
        self.models = MockModels(response_text=response_text, candidates=candidates, raise_error=raise_error)
        # Mirror `.aio` attribute used in service
        self.aio = self

    async def __aenter__(self):
        return self

    async def __aexit__(self, exc_type, exc, tb):
        return False


def mock_genai_client_factory(response_text: Optional[str] = None, candidates: Optional[list] = None, raise_error: Optional[Exception] = None):
    """Return a callable that creates a configured MockGenaiClient instance.

    The GeminiService expects to call `client_factory()` and use the returned
    object's `.aio` as an async context manager.
    """

    def factory():
        return MockGenaiClient(response_text=response_text, candidates=candidates, raise_error=raise_error)

    return factory
